apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: projectmovio/login-service:0.0.2
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "20Mi"
              cpu: "2m"
            limits:
              memory: "30Mi"
              cpu: "100m"